version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "stfsy"
    open-pull-requests-limit: 5

  # Enable version updates for npm (example app)
  - package-ecosystem: "npm"
    directory: "/example"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "stfsy"
    open-pull-requests-limit: 5