name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # For GitHub Actions, we don't need a specific release type
          # release-please will auto-detect based on the repository structure
          release-type: simple